name: 'Geodesic Authenticate'
description: 'Authenticate with Geodesic using an API key'
author: 'SeerAI'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  api-key:
    description: 'Your input description here'
    required: true
    default: '1000'
  geodesic-host:
    description:
      'URL for the Geodesic API. Defaults to the SaaS version
      (https://api.geodesic.seerai.space).'
    required: false
    default: 'https://api.geodesic.seerai.space'

runs:
  using: node20
  main: dist/index.js
